// A26: Python deps are hash-locked and free of the known-vulnerable pins.
// Static checks always run. Live checks run when WT_PY points at a venv python
// that was installed with `pip install --require-hashes -r requirements.txt`.
// The live SSH server listens on 127.0.0.1 only.
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const ROOT = path.resolve(__dirname, '..', '..');
let pass = 0, fail = 0;
function check(name, ok, detail) {
  if (ok) { pass++; console.log(`ok - ${name}`); }
  else { fail++; console.log(`not ok - ${name}${detail ? ' :: ' + detail : ''}`); }
}
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');

// Parse a pip lock file into [{name, version, hashes}] (one entry per pin line).
function parseLock(text) {
  const out = [];
  let cur = null;
  for (const raw of text.split('\n')) {
    const line = raw.replace(/\s+$/, '');
    if (!line || line.trimStart().startsWith('#')) continue;
    const pin = line.match(/^([A-Za-z0-9_.-]+)==([^\s;\\]+)/);
    if (pin) { cur = { name: pin[1].toLowerCase(), version: pin[2], hashes: 0, raw: line }; out.push(cur); }
    else if (!/^\s/.test(line)) { out.push({ name: line, version: null, hashes: 0, raw: line }); cur = null; }
    if (cur && /--hash=sha256:[0-9a-f]{64}/.test(line)) cur.hashes++;
  }
  return out;
}
// Compare dotted versions numerically (enough for these pins).
function ge(v, min) {
  const a = v.split(/[.+-]/).map((x) => parseInt(x, 10) || 0);
  const b = min.split('.').map((x) => parseInt(x, 10));
  for (let i = 0; i < b.length; i++) { if ((a[i] || 0) !== b[i]) return (a[i] || 0) > b[i]; }
  return true;
}
const ver = (lock, n) => lock.filter((p) => p.name === n).map((p) => p.version);

// ---- core lock ----
const core = parseLock(read('requirements.txt'));
check('core lock: has pins', core.length >= 8, String(core.length));
check('core lock: every line is an exact == pin', core.every((p) => p.version), core.filter((p) => !p.version).map((p) => p.raw).join(' | '));
check('core lock: every pin has a sha256 hash', core.every((p) => p.hashes > 0), core.filter((p) => !p.hashes).map((p) => p.name).join(','));
check('core lock: generated by uv with --generate-hashes', /uv pip compile requirements\.in .*--generate-hashes/.test(read('requirements.txt')));
const heavy = ['sentence-transformers', 'lancedb', 'pyarrow', 'torch', 'transformers', 'numpy'];
check('core lock: archiver AI stack is NOT in core', heavy.every((n) => ver(core, n).length === 0), heavy.filter((n) => ver(core, n).length).join(','));
for (const n of ['watchdog', 'psutil', 'paramiko']) check(`core lock: ${n} pinned`, ver(core, n).length === 1, JSON.stringify(ver(core, n)));
check('core lock: paramiko >= 5.0.0 (PYSEC-2026-2858)', ver(core, 'paramiko').every((v) => ge(v, '5.0.0')), JSON.stringify(ver(core, 'paramiko')));
const coreIn = read('requirements.in');
check('requirements.in: lists only watchdog, psutil, paramiko',
  coreIn.split('\n').filter((l) => l.trim() && !l.trim().startsWith('#')).map((l) => l.split('==')[0].trim()).sort().join(',') === 'paramiko,psutil,watchdog');

// ---- archiver lock ----
const arch = parseLock(read('requirements-archiver.txt'));
check('archiver lock: every line is an exact == pin', arch.length > 10 && arch.every((p) => p.version), arch.filter((p) => !p.version).map((p) => p.raw).join(' | '));
check('archiver lock: every pin has a sha256 hash', arch.every((p) => p.hashes > 0), arch.filter((p) => !p.hashes).map((p) => p.name).join(','));
const mins = { 'sentence-transformers': '5.6.0', pyarrow: '23.0.1', transformers: '5.10.0' };
for (const [n, m] of Object.entries(mins)) {
  check(`archiver lock: ${n} >= ${m}`, ver(arch, n).length > 0 && ver(arch, n).every((v) => ge(v, m)), JSON.stringify(ver(arch, n)));
}
check('archiver lock: lancedb pinned', ver(arch, 'lancedb').length === 1);
// Shared pins must agree so both files install into one venv.
const shared = arch.filter((p) => ver(core, p.name).length);
check('archiver lock: shared pins equal core pins',
  shared.every((p) => ver(core, p.name).includes(p.version)), shared.map((p) => `${p.name}=${p.version}`).join(','));

// ---- installers ----
for (const f of ['setup.sh', 'setup.ps1']) {
  const s = read(f);
  const installs = (s.match(/pip install[^\n]*/g) || []);
  check(`${f}: every pip install uses --require-hashes -r requirements.txt`,
    installs.length === 2 && installs.every((l) => /--require-hashes -r requirements\.txt/.test(l)), installs.join(' | '));
  check(`${f}: no --no-deps`, !/--no-deps/.test(s));
  check(`${f}: never writes requirements.txt`, !/>>?\s*requirements\.txt/.test(s));
  check(`${f}: fails closed when requirements.txt is missing`, (s.match(/requirements\.txt missing/g) || []).length === 2);
}
check('setup.sh: syntax', spawnSync('bash', ['-n', path.join(ROOT, 'setup.sh')]).status === 0);
check('secure_update.sh: documents --require-hashes', /pip install --require-hashes -r requirements\.txt/.test(read('secure_update.sh')));

// ---- live (WT_PY) ----
const py = process.env.WT_PY;
if (py) {
  const imp = spawnSync(py, ['-c', 'import watchdog, psutil, paramiko; print(paramiko.__version__)'], { encoding: 'utf8' });
  check('live: core deps import from the hash-locked venv', imp.status === 0, imp.stderr.slice(-300));
  check('live: paramiko runtime >= 5.0.0', imp.status === 0 && ge(imp.stdout.trim(), '5.0.0'), imp.stdout.trim());
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'wt-a26-'));
  const r = spawnSync(py, [path.join(__dirname, 'py_ssh_harness.py'), ROOT, work],
    { encoding: 'utf8', timeout: 60000, env: { PATH: process.env.PATH, PYTHONDONTWRITEBYTECODE: '1' } });
  const line = (r.stdout || '').split('\n').find((l) => l.startsWith('RESULT='));
  let res = {};
  try { res = JSON.parse(line.slice(7)); } catch (e) { /* reported below */ }
  check('live: SSH harness produced a result', !!line, (r.stderr || '').slice(-400));
  check('live: unknown host key rejected (no TOFU)', line && res.unknown_key === null, JSON.stringify(res));
  check('live: no password sent before host key is trusted', res.auth_before_trust === 0, String(res.auth_before_trust));
  check('live: known host key -> scrape succeeds on paramiko 5',
    res.known_key_path === true && res.known_key_output === '0011.2233.4455 Gi1/0/1\n', JSON.stringify(res));
} else {
  console.log('# live checks skipped (set WT_PY to a venv python installed from requirements.txt)');
}

console.log(`\n# python-deps: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
